client_config_backend: settings
client_config:
  client_id: 800031021609-vk2dg18avarvlqveujrreu58jh9js1bb.apps.googleusercontent.com
  client_secret: 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
  auth_uri: https://accounts.google.com/o/oauth2/auth
  token_uri: https://oauth2.googleapis.com/token
  
save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
